# Generated by Django 3.1.1 on 2020-09-26 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admintb',
            fields=[
                ('username', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('email_id', models.EmailField(max_length=25)),
                ('password', models.CharField(max_length=25)),
            ],
        ),
    ]
