# Generated by Django 3.1.1 on 2020-09-26 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getplaced', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('roll_no', models.IntegerField(primary_key=True, serialize=False)),
                ('phone_no', models.IntegerField()),
                ('email_id', models.EmailField(max_length=25)),
                ('branch', models.CharField(max_length=25)),
                ('section', models.IntegerField()),
                ('year', models.IntegerField()),
                ('password', models.CharField(max_length=25)),
                ('username', models.CharField(max_length=25)),
            ],
        ),
    ]
