# Generated by Django 3.1.1 on 2020-09-26 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('getplaced', '0002_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='roll_no',
            field=models.CharField(max_length=25, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=25)),
                ('project_des', models.CharField(max_length=25)),
                ('tech_stack', models.CharField(max_length=25)),
                ('roll_no', models.ForeignKey(db_column='roll_no', on_delete=django.db.models.deletion.CASCADE, to='getplaced.student')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(upload_to='')),
                ('roll_no', models.ForeignKey(db_column='roll_no', on_delete=django.db.models.deletion.CASCADE, to='getplaced.student')),
            ],
        ),
    ]
