# Generated by Django 3.1.1 on 2020-09-26 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getplaced', '0003_auto_20200926_2156'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
    ]
