# Generated by Django 3.1.1 on 2020-09-26 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('getplaced', '0004_auto_20200926_2158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=25)),
                ('job_title', models.CharField(max_length=25)),
                ('job_description', models.CharField(max_length=25)),
                ('requisites', models.CharField(max_length=25)),
                ('selection_process', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Placement_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=25)),
                ('students_applied', models.IntegerField()),
                ('students_placed', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Suggestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mock_tests', models.URLField()),
                ('tips', models.CharField(max_length=25)),
                ('video_links', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('place', models.CharField(max_length=25)),
                ('roll_no', models.ForeignKey(db_column='roll_no', on_delete=django.db.models.deletion.CASCADE, to='getplaced.student')),
            ],
        ),
    ]
