# Generated by Django 3.1.1 on 2020-11-04 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getplaced', '0005_interview_details_placement_history_register_suggestions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studtb',
            fields=[
                ('username', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=25)),
            ],
        ),
    ]
