# Generated by Django 3.1.1 on 2020-11-04 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getplaced', '0006_studtb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studtb',
            old_name='username',
            new_name='Username',
        ),
        migrations.RenameField(
            model_name='studtb',
            old_name='password',
            new_name='pwd',
        ),
    ]
