# Generated by Django 3.1.1 on 2020-11-05 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getplaced', '0007_auto_20201104_1238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='phone_no',
            new_name='phoneno',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='password',
            new_name='psd',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='section',
            new_name='sec',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='year',
            new_name='syear',
        ),
    ]
