# Generated by Django 3.1.1 on 2020-11-05 14:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('getplaced', '0008_auto_20201105_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='studname',
            field=models.CharField(default=django.utils.timezone.now, max_length=25),
            preserve_default=False,
        ),
    ]
