# Generated by Django 3.1.1 on 2020-11-13 06:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('getplaced', '0009_student_studname'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestions',
            name='added_on',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suggestions',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=25),
            preserve_default=False,
        ),
    ]
