# Generated by Django 3.1.1 on 2020-11-13 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getplaced', '0012_auto_20201113_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placement_history',
            name='package',
            field=models.CharField(max_length=25),
        ),
    ]
