# Generated by Django 3.1.1 on 2020-11-13 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getplaced', '0013_auto_20201113_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placement_history',
            name='package',
        ),
    ]
