# Generated by Django 3.1.1 on 2020-11-13 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getplaced', '0014_remove_placement_history_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='placement_history',
            name='package',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='placement_history',
            name='pyear',
            field=models.IntegerField(),
        ),
    ]
