# Generated by Django 3.1.1 on 2020-11-14 05:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('getplaced', '0015_auto_20201113_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview_details',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interview_details',
            name='link',
            field=models.URLField(default='https://www.facebook.com'),
        ),
        migrations.AddField(
            model_name='interview_details',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
