# Generated by Django 3.1.1 on 2020-11-14 06:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('getplaced', '0016_auto_20201114_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview_details',
            name='added_by',
            field=models.CharField(default=django.utils.timezone.now, max_length=25),
            preserve_default=False,
        ),
    ]
