# Generated by Django 3.1.1 on 2020-11-14 06:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('getplaced', '0017_interview_details_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview_details',
            name='added_on',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
