# Generated by Django 3.1.1 on 2020-11-16 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getplaced', '0018_interview_details_added_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abt', models.CharField(max_length=25)),
                ('skl', models.CharField(max_length=25)),
                ('prjdesc', models.CharField(max_length=25)),
                ('prjlink', models.URLField()),
                ('reslink', models.URLField()),
            ],
        ),
    ]
