# Generated by Django 3.1.1 on 2020-11-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getplaced', '0020_sprofile_usern'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestions',
            name='tips',
            field=models.TextField(),
        ),
    ]
