# Generated by Django 3.1.1 on 2020-11-21 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getplaced', '0021_auto_20201121_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview_details',
            name='job_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='interview_details',
            name='requisites',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='interview_details',
            name='selection_process',
            field=models.TextField(),
        ),
    ]
