# Generated by Django 3.1.1 on 2020-11-23 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getplaced', '0023_auto_20201121_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phoneno',
            field=models.CharField(max_length=10),
        ),
    ]
